# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]

handlers:

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- ^src$
- ^e2e$
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json
- ^.angular\-cli\.json
- ^.editorconfig
- ^.gitignore
- ^.tsconfig\.json
- ^sw-precache.config.js
