import {  InMemoryDbService }  from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
   createDb() {
     let heroes = [
       {id: 11, name: 'Batman', about: `Batman's secret identity is Bruce Wayne, a wealthy American playboy, philanthropist, and owner of Wayne Enterprises. After witnessing the murder of his parents Dr. Thomas Wayne and Martha Wayne as a child, he swore vengeance against criminals, an oath tempered by a sense of justice. Wayne trains himself physically and intellectually and crafts a bat-inspired persona to fight crime. Batman operates in the fictional Gotham City, with assistance from various supporting characters, including his butler Alfred, police commissioner Gordon, and vigilante allies such as Robin. Unlike most superheroes, Batman does not possess any superpowers; rather, he relies on his genius intellect, physical prowess, martial arts abilities, detective skills, science and technology, vast wealth, intimidation, and indomitable will. A large assortment of villains make up Batman's rogues gallery, including his archenemy, the Joker.`},

       {id: 12, name: 'Super Girl', about: `At 12 years old, Kara Zor-El escapes doom on planet Krypton to find protection on Earth with the Danver family, where she grows up in the shadow of her foster sister, Alex, and learns to hide the extraordinary powers she shares with her cousin, Superman. Now an adult living in National City and working for media mogul Cat Grant, Kara finds her days of keeping her abilities a secret are over when super-secret agency head Hank Henshaw enlists her to help protect the city's citizens from threats. Finally coming into her own, Kara must juggle her new responsibilities with her very human relationships.`},

       {id: 13, name: 'The Flash', about: `At 11, Barry Allen's life changed completely when his mother died in a freak accident and his innocent father was convicted of her murder. Now a crime-scene investigator, his dedication to learn the truth about his mother's death drives him to follow up on every new scientific advancement and urban legend. When his latest obsession -- a particle accelerator heralded as a world-changing invention -- causes an explosion, it creates a freak storm and Barry is struck by lightning. He awakes from a coma nine months later with the power of superspeed. When he learns that others who have gained powers use them for evil, he dedicates himself to protecting the innocent, while still trying to solve the older mystery.`},

       {id: 14, name: 'Super Man', about: `The origin story of Superman relates that he was born Kal-El on the planet Krypton, before being rocketed to Earth as an infant by his scientist father Jor-El, moments before Krypton's destruction. Discovered and adopted by a Kansas farm couple, the child is raised as Clark Kent and imbued with a strong moral compass. Very early on he started to display various superhuman abilities, which, upon reaching maturity, he resolved to use for the benefit of humanity through a secret "Superman" identity.

        Superman resides and operates in the fictional American city of Metropolis. As Clark Kent, he is a journalist for the Daily Planet, a Metropolis newspaper. Superman's love interest is generally Lois Lane, and his archenemy is the supervillain Lex Luthor. He is typically a member of the Justice League and close ally of Batman and Wonder Woman. Like other characters in the DC Universe, several alternate versions of Superman have been depicted over the years.`},

       {id: 15, name: 'Captain America', about:`Captain America is a fictional superhero appearing in American comic books published by Marvel Comics. Created by cartoonists Joe Simon and Jack Kirby, the character first appeared in Captain America Comics #1 (cover dated March 1941) from Timely Comics, a predecessor of Marvel Comics. Captain America was designed as a patriotic supersoldier who often fought the Axis powers of World War II and was Timely Comics' most popular character during the wartime period. The popularity of superheroes waned following the war and the Captain America comic book was discontinued in 1950, with a short-lived revival in 1953. Since Marvel Comics revived the character in 1964, Captain America has remained in publication.`},

       {id: 16, name: 'Suicide Squad', about: `Suicide Squad is a 2016 American superhero film based on the DC Comics antihero team of the same name. It is the third installment in the DC Extended Universe series. The film was written and directed by David Ayer and stars an ensemble cast consisting of Will Smith, Jared Leto, Margot Robbie, Joel Kinnaman, Viola Davis, Jai Courtney, Jay Hernandez, Adewale Akinnuoye-Agbaje, Ike Barinholtz, Scott Eastwood, and Cara Delevingne. In the film, a secret government agency led by Amanda Waller recruits imprisoned supervillains to execute dangerous black ops missions and save the world from a powerful threat, in exchange for reduced sentences.

        By February 2009, a Suicide Squad film was in development at Warner Bros. Ayer signed on to write and direct in September 2014, and by October, the casting process had begun. Principal photography began on April 13, 2015 in Toronto, Ontario with additional filming in Chicago, Illinois, and ended in August that year.`},

       {id: 17, name: 'Black Panter', about: `The Black Panther (T'Challa) is a fictional superhero appearing in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and penciller and co-plotter Jack Kirby, he first appeared in Fantastic Four #52 (July 1966). He is the first black superhero in mainstream American comics, debuting years before such early African-American superheroes as Marvel Comics' the Falcon (1969) and Luke Cage (1972), and DC Comics' Green Lantern John Stewart (1971) and Black Lightning (1977). The character is usually depicted as the king and protector of Wakanda, a fictional African nation. Chadwick Boseman portrays the Black Panther in Captain America: Civil War (2016) and is set to return in Black Panther (2018), both set in the Marvel Cinematic Universe.`},

       {id: 18, name: 'Spiderman', about: `Spider-Man is a fictional superhero appearing in American comic books published by Marvel Comics. The   character was created by writer-editor Stan Lee and writer-artist Steve Ditko, and first appeared in the anthology comic book Amazing Fantasy #15 (Aug. 1962) in the Silver Age of Comic Books. Lee and Ditko conceived the character as an orphan being raised by his Aunt May and Uncle Ben, and as a teenager, having to deal with the normal struggles of adolescence in addition to those of a costumed crime-fighter. Spider-Man's creators gave him super strength and agility, the ability to cling to most surfaces, shoot spider-webs using wrist-mounted devices of his own invention, which he calls web-shooters, and react to danger quickly with his spider-sense, enabling him to combat his foes.`},

       {id: 19, name: 'WonderWoman', about: `Wonder Woman is a fictional superhero appearing in American comic books published by DC Comics.The character is a founding member of the Justice League, demigoddess, and warrior princess of the Amazonian people. In her homeland, she is Princess Diana of Themyscira, and outside of her homeland, she is known by her civilian identity Diana Prince.

          Wonder Woman was created by the American psychologist and writer William Moulton Marston, and artist Harry G. Peter. He and his wife Elizabeth's cohabitant, Olive Byrne, is credited as being Marston's inspiration for the character's appearance. Marston drew a great deal of inspiration from early feminists, and especially from birth control pioneer Margaret Sanger. The character first appeared in All Star Comics #8 in October 1941 and first cover-dated on Sensation Comics #1, January 1942. The Wonder Woman title has been published by DC Comics almost continuously except for a brief hiatus in 1986.`},

       {id: 20, name: 'Arrow', about: `When presumed-dead billionaire playboy Oliver Queen returns home to Starling City after five years stranded on a remote island in the Pacific, he hides the ways the experience has changed him. As he reconnects with those closest to him, including his sister, Thea, Oliver appears to be the same wealthy, carefree bachelor they've always known. At night, flanked by his devoted friend, Diggle, Oliver uses his secret persona -- that of a vigilante -- to right societal wrongs and transform the city to its former glory.`},

       {id: 21, name: 'DeadPool', about: `Wade Wilson (Ryan Reynolds) is a former Special Forces operative who now works as a mercenary. His world comes crashing down when evil scientist Ajax (Ed Skrein) tortures, disfigures and transforms him into Deadpool. The rogue experiment leaves Deadpool with accelerated healing powers and a twisted sense of humor. With help from mutant allies Colossus and Negasonic Teenage Warhead (Brianna Hildebrand), Deadpool uses his new skills to hunt down the man who nearly destroyed his life.`}
     ];
     return {heroes};
   }
}
